version: '3.7'
services:
  frontend:
    image: antoniopapa1991/admin-frontend
    ports:
      - 8080:80
    depends_on:
      - server
    networks:
      - app

  server:
    container_name: influencer_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_DATABASE: influencer
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_URL: "http://localhost:8014"
      MAIL_HOST: mailcatcher
      REDIS_HOST: redis
    restart: always
    ports:
      - 8014:8000
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    networks:
      - app

  database:
    container_name: influencer_db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: influencer
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    restart: always
    ports:
      - 3016:3306
    networks:
      - app

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - app

  mailcatcher:
    container_name: mailcatcher
    image: dockage/mailcatcher:0.6.5
    restart: always
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - app

  composer:
    build:
      context: .
      dockerfile: composer.Dockerfile
    volumes:
      - .:/app
    networks:
      - app

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: [ "php", "/app/artisan" ]
    networks:
      - app

networks:
  app: null
